name: Test
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set env vars
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: .tool-versions
      - name: cache go binaries
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        id: cache-go-bin
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-${{ hashFiles('**/go.mod') }}
          restore-keys: ${{ runner.os }}-go-bin
      - name: test
        run: make test

  precommit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: .tool-versions
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: "3.x"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
        with:
          extra_args: --show-diff-on-failure --from-ref ${{
            github.event.pull_request.base.sha }} --to-ref ${{
            github.event.pull_request.head.sha }}
        env:
          SKIP: lint
