name: Test
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set env vars
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: .tool-versions
      - name: cache go binaries
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        id: cache-go-bin
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-${{ hashFiles('**/go.mod') }}
          restore-keys: ${{ runner.os }}-go-bin
      - name: test
        run: make test
      - name: check debug image contract
        run: ./scripts/check-debug-image-contract

  precommit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: .tool-versions
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.x"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
        with:
          extra_args: --show-diff-on-failure --from-ref ${{
            github.event.pull_request.base.sha }} --to-ref ${{
            github.event.pull_request.head.sha }}
        env:
          SKIP: lint
